user:
  username: ding
  hobby: basketball,football
  
spring:
  profiles:
    active: dev #指定使用哪个环境
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: test
---
server:
  port: 8084
spring:
 profiles: prod